version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - php_sessions:/var/lib/php/sessions
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=dbuser
      - DB_PASSWORD=dbpassword
      - DB_NAME=job_finder

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=job_finder
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbpassword

volumes:
  mysql_data:
  php_sessions: